Feature 4.3
IgorKruchinin/TKI-141 pull request #5
Opened 2023-09-22 14:40 UTC by IgorKruchinin

2023-09-29 06:25 UTC, MarinaPaley requested changes
Добавьте перечислимый тип

2023-09-29 06:25 UTC, MarinaPaley commented on main.c
> +}
Переместить после `main()`

2023-09-29 06:25 UTC, MarinaPaley commented on main.c
> +}
Реализация - после `main()`

2023-09-29 06:25 UTC, MarinaPaley commented on main.c
> +	scanf("%d %d", &n, &m);
```c
int n = getSize("Enter n = ");
int m = getSize("Enter m = ");
int** arr = getArray(n, m);
...

2023-09-29 06:25 UTC, MarinaPaley commented on main.c
> +	int j = 0;
https://replit.com/@MarinaPaley/WebbedWobblyTabs#main.c

2023-09-29 06:25 UTC, MarinaPaley commented on main.c
> +	}
В отдельную функцию

2023-09-29 06:25 UTC, MarinaPaley commented on main.c
> +	}
В отдельную функцию.

2023-09-29 06:25 UTC, MarinaPaley commented on main.c
> +	}
В отдельную функцию.

2023-09-29 06:25 UTC, MarinaPaley commented on task-4.3/main.c
> +void printArr(int **arr, int n, int m);
https://en.cppreference.com/w/c/types/size_t

2023-09-29 06:25 UTC, MarinaPaley commented on task-4.3/main.c
> +	puts("\nDo you want to enter the array or fill it random digits? (0 - for enter, 1 - for random): ");
https://replit.com/@MarinaPaley/WebbedWobblyTabs#main.c

2023-09-29 06:27 UTC, MarinaPaley commented
Для работы с массивами используйте тип `size_t`. Он беззнаковый. Но, когда вводите из консоли  - вводите `int`, затем проверяйте  введенное на неотрицательность, и только потом приводите к типу `size_t`.

2023-09-29 13:42 UTC, IgorKruchinin commented
Исправил, я видел, что у вас версия кода старее, поэтому у вас функции отображаются перед main, на момент PR это уже было исправлено. Поэтому кидаю номер Commit последнего изменения: https://github.com/IgorKruchinin/TKI-141/commit/d95e9ddc03df379652ca7fedb410f8beb5153f80

2023-09-29 13:43 UTC, IgorKruchinin commented
3.2 тоже скоро поправлю на безопасный ввод

2023-09-29 13:53 UTC, IgorKruchinin commented
Последний Commit: https://github.com/IgorKruchinin/TKI-141/commit/d42821eeba18927814410027af4df461d434656a

2023-09-29 13:53 UTC, IgorKruchinin commented
Последний Commit для задания 3.2: https://github.com/IgorKruchinin/TKI-141/commit/d42821eeba18927814410027af4df461d434656a

2023-09-29 15:05 UTC, IgorKruchinin commented
Поправил документацию в 3.2: https://github.com/IgorKruchinin/TKI-141/commit/9483ecee74d34b1210d505f711b133a011efd0d2

2023-09-30 19:22 UTC, IgorKruchinin commented
Добавлено освобождение памяти массива для избежания утечки памяти: ccabf07b65e173b1350e49bc1582ebbf305b07fd

2023-10-03 09:57 UTC, IgorKruchinin commented
Исправлено использование функции getChoice: Commit: 5247b939c36e7aeb2223c41990d5c88a073c11a0

2023-10-03 11:43 UTC, merged