Solve 3.2
IgorKruchinin/TKI-141 pull request #6
Opened 2023-09-26 21:51 UTC by IgorKruchinin

2023-09-29 13:52 UTC, IgorKruchinin commented
Последний Commit: https://github.com/IgorKruchinin/TKI-141/commit/d42821eeba18927814410027af4df461d434656a

2023-09-29 15:04 UTC, IgorKruchinin commented
Поправил документацию: https://github.com/IgorKruchinin/TKI-141/commit/9483ecee74d34b1210d505f711b133a011efd0d2

2023-10-03 11:17 UTC, MarinaPaley requested changes

2023-10-03 11:17 UTC, MarinaPaley commented on task-4.3/main.c
> +void printArr(int **arr, int n, int m);
`size_t`

2023-10-03 11:17 UTC, MarinaPaley commented on task-4.3/main.c
> +int main() {
https://replit.com/@MarinaPaley/WebbedWobblyTabs

2023-10-03 11:17 UTC, MarinaPaley commented on task-4.3/main.c
> +	if (scanf("%d %d", &n, &m) != 2) {
`int getInt("Введите ...");`

2023-10-03 11:17 UTC, MarinaPaley commented on task-4.3/main.c
> +	if (m <= 0 || n <= 0) {
```c
size_t checkSize(int* size)
{
  if (size <= 0)
  {
    puts("Error");
    abort();
  }
returm (size_t)size;
}
```

}

2023-10-03 11:17 UTC, MarinaPaley commented on task-4.3/main.c
> +	int i = 0;
`size_t`

2023-10-03 11:17 UTC, MarinaPaley commented on task-4.3/main.c
> +				if (scanf("%d", &((*arr)[i][j])) != 1) {
`(*arr)[i][j]) = getInt()`

2023-10-03 11:17 UTC, MarinaPaley commented on task-4.3/main.c
> +int findMax(int ***arr, int n, int m) {
`const int** arr,...`

2023-10-03 11:42 UTC, merged