Computing of factorial was speed up
IgorKruchinin/TKI-141 pull request #8
Opened 2023-10-06 15:35 UTC by IgorKruchinin

Для ускорения вычисления факториала каждый новый факториал вычисляется как предыдущий факториал умножить на текущее k. Гораздо проще и логичнее сделать вычисление факториала и последовательности в одной функции, так код более понятен.

2023-10-10 08:22 UTC, MarinaPaley requested changes
Задание на рекуррентную формулу

2023-10-12 06:15 UTC, IgorKruchinin commented
Commit: f034fd5eb1c20445bbd495ed56f22b2a6002d617

2023-10-17 08:42 UTC, MarinaPaley approved these changes

2023-10-17 08:42 UTC, MarinaPaley commented on task-3.2/main.c
>  	double b = (double)func(n + 1);
Кроме названий, которые неговорящие, кажется, что правильно. Если расчет совпадает с тестовым, то хорошо.
Используйте говорящие названия `current`, `next`, 'previous`.

2023-10-17 10:52 UTC, merged